services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointmate
      MYSQL_USER: appointmate_user
      MYSQL_PASSWORD: appointmate_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./DATABASE/appointmate.sql:/docker-entrypoint-initdb.d/appointmate.sql

volumes:
  db_data:
